export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";


export const ORDER_REPORT_REQUEST = "ORDER_REPORT_REQUEST";
export const ORDER_REPORT_SUCCESS = "ORDER_REPORT_SUCCESS";
export const ORDER_REPORT_FAIL = "ORDER_REPORT_FAIL";
